### ISSUE TITLE
Preferred citation

### ISSUE THREAD

**Issue by luisgerhorst** [jwnhy/MOAT-Open#1]
Hey, great work! What's your preferred method to (academically) cite MOAT?

**Comment by jwnhy** [comment]
Hi, thank you for your interest, this manuscript is still under review.
For now, please cite our paper in the Arxiv format. We will update the citation if the paper status changes.

```
@misc{lu2023moat,
      title={MOAT: Towards Safe BPF Kernel Extension}, 
      author={Hongyi Lu and Shuai Wang and Yechang Wu and Wanning He and Fengwei Zhang},
      year={2023},
      eprint={2301.13421},
      archivePrefix={arXiv},
      primaryClass={cs.CR}
}
```
